config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|it/ do

    devise_for :users, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      registration: 'register'
    }

    root 'static_pages#home'
    resources :guests, only: [:index]
    resources :messages, only: [:index]
    resources :places, only: [:index]

  end

  resources :guests, only: [:create, :destroy] do
    collection do
      get :datatable_list
    end
  end

  resources :messages, only: [:create] do
    collection do
      get :datatable_list
    end
  end
  
  resources :places, only: [:create] do
    collection do
      get :datatable_list
    end
  end

  resources :users, only: [] do
    collection do
      get :check
      post :update_password
    end
  end
 

end

app/models/message.rb
class Message  < ActiveRecord::Base

  belongs_to :user
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include DatatableList

  before_action :authenticate_user!

  def index
  end

  def create
    
    begin
      m = JSON.parse(msg_params.fetch("message_json")).with_indifferent_access
      Message.create!(text: m[:text], phone_number: m[:phone_number], user: current_user)
      @status = "success"
    rescue ActiveRecord::RecordInvalid
      @status = "invalid input"
    end
   
    respond_to do |format|
      format.json { render json:{ status: @status }  }
    end

  end

  private

    def msg_params
      params.permit(:message_json)
    end

end

app/views/messages/_header.html.haml
/ Instructions: Set your background image using the URL below.
%header{ style: "background-image: url(#{asset_path('img/valdemossa.jpg')})" }
  %aside.header-quote
    .container.wow.fadeIn
      .row
        .col-md-10.col-md-offset-1
          %span.quote
            %span.text-primary= t('header.text-primary')
          %hr.colored
          %span.quote= t('header.quote')
          %br

  .scroll-down
    %a.btn.page-scroll{ href: "#message_table" }
      %i.fa.fa-angle-down.fa-fw

app/views/messages/index.html.haml
- provide :page_title do
  %title Mauro e Beatrice | Message List
- provide :page_stylesheet do
  = stylesheet_link_tag "css/dataTables.bootstrap.css"

= render partial: 'header'

%section#message_table.bg-gray
  .container.wow.fadeIn
    .row
      .col-lg-12.text-center
        %h2= t('message_table.title')
        %hr.colored/
        %p= t('message_table.description')
    .row
      %br/
    .row
      .table-responsive
        %table.table.table-striped#messages
          %thead
            %tr
              %th= t('message_table.table.headers.email')
              %th= t('message_table.table.headers.phone_number')
              %th= t('message_table.table.headers.text')
              %th= t('message_table.table.headers.created_at')

- provide :page_javascript do
  = javascript_include_tag "js/jquery.dataTables.min.js"
  = javascript_include_tag "js/dataTables.bootstrap.min.js"
  :coffee
    $("#messages").DataTable
      'language': I18n.t('datatables')
      'processing': true
      'pageLength': 50
      'order': [[ 0, 'desc' ]]
      'processing': true
      'ordering': true
      'dom': 'fl<"table-scrollable"t>irp'
      'columnDefs': [ {targets: [], orderable: true}]
      'ajax': '#{datatable_list_messages_path}'