config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|it/ do

    devise_for :users, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      registration: 'register'
    }

    root 'static_pages#home'
    resources :guests, only: [:index]
    resources :messages, only: [:index]
    resources :places, only: [:index]

  end

  resources :guests, only: [:create, :destroy] do
    collection do
      get :datatable_list
    end
  end

  resources :messages, only: [:create] do
    collection do
      get :datatable_list
    end
  end
  
  resources :places, only: [:create] do
    collection do
      get :datatable_list
    end
  end

  resources :users, only: [] do
    collection do
      get :check
      post :update_password
    end
  end
 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_action :authenticate_user!

  def home
    @guests = Guest.where(user: current_user).all
    @suggestions = Place.all.map{|p| p.marker} || []
  end

  def help
  end
end

app/views/static_pages/javascripts/_guests.js.erb
var guestList = <%= @guests.to_json.html_safe %>;
// var validationKey = "e0d67e387659dc93136877f61d49bc33ad5568d03b2a4b887d2e81403c26bc0ea11677b2296d09629a1b3527a90dca4e4b235f882e3327e9c9e1db9815549cbc";

$(document).ready(function() {
  // $("#participation-form").hide();
  renderGuestsTable();
});

/*
$("#check-code").click(function(){

  var validationCode = encrypt( $("#guest_validation").val().trim() );

  if (validationCode === validationKey) {

    $("#validation-form").hide();
    $("#participation-form").show();
    renderGuestsTable();
    return;
  }

  $("#error-validation").html("Il codice di verifica inserito non è corretto");

})

$("#add-guest").click(function() {
  
  $("#error-input").html("");
  $("#success-input").html("");

  var name = capitalize( $("#guest_name").val().trim().toLowerCase() ),
      surname = capitalize(  $("#guest_surname").val().trim().toLowerCase() );
  
  if (name === "" || surname  === "") {
    $("#error-input").html("Tutti i campi devono essere compilati");
    return;
  }

  var item = {
    name: name,
    surname: surname
  };

  var found = false;
  $.each(guestList, function( index, value ) {
    if (value["name"] == name & value["surname"] == surname) {
      found = true;
    }
  });
  if (found) {
    var error_template = "{name} {surname} è già stato inserito";
    $("#error-input").html(supplant(error_template, item));
    return;
  }

  createGuest(item);
  var success_template = "{name} {surname} è stato inserito con successo";
  $("#success-input").html(supplant(success_template, item));
})

function createGuest(item){

  var request = $.ajax({
    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
    url: '<%= guests_path %>',
    dataType: 'json',
    type: "POST",
    quietMillis: 200,
    data: { guest_json: JSON.stringify(item)}
    });

  request.done(function(data){
      guestList = JSON.parse(data["guest_list"]);
      renderGuestsTable();
  });
}
*/

function renderGuestsTable() {
  var template = $.templates("#added-guests-template");
  var htmlGuestList = template.render(guestList);
  $("#added-guests-container").html(htmlGuestList);  
}
/*
function removeGuest(id_to_delete) {
  var request = $.ajax({
    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
    url: '<%= guest_path(id: "id_to_delete") %>'.replace("id_to_delete", id_to_delete),
    type: "DELETE",
    quietMillis: 200
    });

  request.done(function(data){
    if (data["status"] == "success"){
      console.log(data["guest_list"]);      
    }
    guestList = JSON.parse(data["guest_list"]);
    renderGuestsTable();
  });
}
*/

app/views/static_pages/javascripts/_maps_search_box.js.erb
var suggestionsList = <%= @suggestions.to_json.html_safe %> ;

function loadMakers(markerObj){
  var markers = [] ;

  suggestionsList.forEach(function(elem, index){
    markers.push(new markerObj(
      {map: map,
       icon: elem.icon, 
       title: elem.title,
       position: elem.position}));
    });
  return markers;
}

function initAutocomplete() {
  map = new google.maps.Map(document.getElementById('map'), {
    center: {lat: 42.991843, lng: 12.495453},
    zoom: 6,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  
  searchInput = document.getElementById('pac-input');
  searchBox = new google.maps.places.SearchBox(searchInput);

  // Create the search box and link it to the UI element.
  map.controls[google.maps.ControlPosition.TOP_LEFT].push(searchInput);
  processAndDrawMap();

};

function processAndDrawMap(){
  // Bias the SearchBox results towards current map's viewport.
  map.addListener('bounds_changed', function() {
    searchBox.setBounds(map.getBounds());
  });

  var markers = loadMakers(google.maps.Marker);
  // Listen for the event fired when the user selects a prediction and retrieve
  // more details for that place.
  searchBox.addListener('places_changed', function() {
    var places = searchBox.getPlaces();

    if (places.length == 0) {
      return;
    }

    if (places.length >1){
      // If the result is more than one place, take the first only
      places = [ places[0] ]
    }
    // For each place, get the icon, name and location.
    var bounds = new google.maps.LatLngBounds();
    places.forEach(function(place) {
      var icon = {
        url: place.icon,
        size: new google.maps.Size(71, 71),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(17, 34),
        scaledSize: new google.maps.Size(25, 25)
      };

      // Create a marker for each place.
      var marker = {
        map: map,
        icon: icon,
        title: place.name,
        position: place.geometry.location
      };

      var fullAddress = place.formatted_address;

      $('#suggestionTitle').html(place.name);
      $('#searchMapModal').modal('show');
      $('#suggestion-submit').click(function(){
          var reason = $("#suggestion-reason").val();

          markers.push(new google.maps.Marker(marker));
          createMarker(marker, reason, fullAddress);
          if (place.geometry.viewport) {
          // Only geocodes have viewport.
          bounds.union(place.geometry.viewport);
          } else {
          bounds.extend(place.geometry.location);
          }
      });

    });

    // map.fitBounds(bounds);
  });
}

function createMarker(item, text, address){

  var request = $.ajax({
    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
    url: '<%= places_path %>',
    dataType: 'json',
    type: "POST",
    quietMillis: 200,
    data: { marker: JSON.stringify(item, function(key,value){
              if(key == "map"){
                  return undefined;
              }
              return value;
              }),
            reason: text,
            address: address }
    });

  request.done(function(data){
      suggestionsList = JSON.parse(data.markers);
      processAndDrawMap();
  });
};

app/views/static_pages/javascripts/_messages.js.erb
$("#contact-button").click(function(){

  var contactMessage = {
    phone_number: $("#contact-phone_number").val().trim(),
    text: $("#contact-msg").val().trim()
  }

  if (contactMessage.text == "") {
    alert('<%= t("contact.form.message.error") %>');
    return;
    }

  createMessage(contactMessage);

  })


function createMessage(item){

  var request = $.ajax({
    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
    url: '<%= messages_path %>',
    dataType: 'json',
    type: "POST",
    quietMillis: 200,
    data: { message_json: JSON.stringify(item)}
    });

  request.done(function(data){
      alert('<%= t("contact.success") %>');
  });
}