config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|it/ do

    devise_for :users, controllers: {
      passwords: 'users/passwords',
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }, path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      password: 'secret',
      registration: 'register'
    }

    root 'static_pages#home'
    resources :guests, only: [:index]
    resources :messages, only: [:index]
    resources :places, only: [:index]

  end

  resources :guests, only: [:create, :destroy] do
    collection do
      get :datatable_list
    end
  end

  resources :messages, only: [:create] do
    collection do
      get :datatable_list
    end
  end
  
  resources :places, only: [:create] do
    collection do
      get :datatable_list
    end
  end

  resources :users, only: [] do
    collection do
      get :check
      post :update_password
    end
  end
 

end

app/models/place.rb
class Place  < ActiveRecord::Base

  belongs_to :user
  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  include DatatableList

  before_action :authenticate_user!

  def index
  end

  def create
    
    begin
      marker = JSON.parse(marker_params.fetch("marker"))
      reason = marker_params.fetch(:reason)
      full_address = marker_params.fetch(:address)
      Place.create!(marker: marker, user: current_user, reason: reason, address: full_address)
      @status = "success"
    rescue ActiveRecord::RecordInvalid
      @status = "invalid input"
    end

    places = Place.all.map{ |p| p.marker }
    
    respond_to do |format|
      format.json { render json:{ markers: places.to_json, status: @status }  }
    end

  end

  private

  def marker_params
    params.permit(:marker, :reason, :address)
  end
end

app/views/places/_header.html.haml
/ Instructions: Set your background image using the URL below.
%header{ style: "background-image: url(#{asset_path('img/valdemossa.jpg')})" }
  %aside.header-quote
    .container.wow.fadeIn
      .row
        .col-md-10.col-md-offset-1
          %span.quote
            %span.text-primary= t('header.text-primary')
          %hr.colored
          %span.quote= t('header.quote')
          %br

  .scroll-down
    %a.btn.page-scroll{ href: "#place_table" }
      %i.fa.fa-angle-down.fa-fw

app/views/places/index.html.haml
- provide :page_title do
  %title Mauro e Beatrice | Suggested Place List
- provide :page_stylesheet do
  = stylesheet_link_tag "css/dataTables.bootstrap.css"

= render partial: 'header'

%section#place_table.bg-gray
  .container.wow.fadeIn
    .row
      .col-lg-12.text-center
        %h2= t('place_table.title')
        %hr.colored/
        %p= t('place_table.description')
    .row
      %br/
    .row
      .table-responsive
        %table.table.table-striped#places
          %thead
            %tr
              %th= t('place_table.table.headers.address')
              %th= t('place_table.table.headers.reason')
              %th= t('place_table.table.headers.email')

- provide :page_javascript do
  = javascript_include_tag "js/jquery.dataTables.min.js"
  = javascript_include_tag "js/dataTables.bootstrap.min.js"
  :coffee
    $("#places").DataTable
      'language': I18n.t('datatables')
      'processing': true
      'pageLength': 50
      'order': [[ 0, 'desc' ]]
      'processing': true
      'ordering': true
      'dom': 'fl<"table-scrollable"t>irp'
      'columnDefs': [ {targets: [], orderable: true}]
      'ajax': '#{datatable_list_places_path}'